#!/usr/bin/env julia

# Developer-only full-stack fit driver. This file reads the fixtures generated by
# generate_data.jl and writes fit outputs under test/fullstack/results/.
#
# It is intentionally not included from test/runtests.jl.

using Random

using StochasticGene

include(joinpath(@__DIR__, "generate_data.jl"))

const FULLSTACK_RESULTFOLDER = "results"

function _fullstack_common_kwargs(; resultfolder::AbstractString=FULLSTACK_RESULTFOLDER)
    return (
        root=DEFAULT_ROOT,
        infolder="data",
        resultfolder=resultfolder,
        cell=FULLSTACK_CELL,
        writesamples=false,
        optimize=false,
        burst=false,
    )
end

function _fullstack_sampling_kwargs(;
    inference_method::Symbol=:mh,
    samplesteps::Integer=40,
    warmupsteps::Integer=0,
    maxtime::Real=60.0,
    nchains::Integer=1,
    kwargs...,
)
    return (
        inference_method=inference_method,
        samplesteps=Int(samplesteps),
        warmupsteps=Int(warmupsteps),
        maxtime=Float64(maxtime),
        nchains=Int(nchains),
        kwargs...,
    )
end

function _rna_model_kwargs(unit::Integer=1)
    rates = collect(Float64, COUPLED_UNIT_RNA_RATES[unit])
    return (
        transitions=DEFAULT_TRANSITIONS,
        G=DEFAULT_G,
        R=1,
        S=0,
        insertstep=1,
        nalleles=DEFAULT_NALLELES,
        rinit=rates,
        priormean=rates,
        decayrate=rates[StochasticGene.num_rates(DEFAULT_TRANSITIONS, 1, 0, 1)],
        fittedparam=Int[1, 2],
        propcv=0.05,
        priorcv=10.0,
    )
end

function _trace_model_kwargs()
    rates = collect(Float64, COUPLED_RATES[1:9])
    return (
        transitions=DEFAULT_TRANSITIONS,
        G=DEFAULT_G,
        R=1,
        S=0,
        insertstep=1,
        nalleles=1,
        rinit=rates,
        priormean=rates,
        decayrate=rates[StochasticGene.num_rates(DEFAULT_TRANSITIONS, 1, 0, 1)],
        fittedparam=Int[1, 2],
        propcv=0.05,
        priorcv=10.0,
        noisepriors=[0.0, 0.1, 1.0, 0.1],
        zeromedian=false,
    )
end

function _tracejoint_model_kwargs()
    rates = collect(Float64, COUPLED_RATES)
    return (
        transitions=COUPLED_TRANSITIONS,
        G=COUPLED_G,
        R=COUPLED_R,
        S=COUPLED_S,
        insertstep=COUPLED_INSERTSTEP,
        coupling=COUPLED_COUPLING,
        nalleles=1,
        rinit=rates,
        priormean=rates,
        decayrate=(COUPLED_RATES[5], COUPLED_RATES[14]),
        fittedparam=Int[19],
        propcv=0.05,
        priorcv=10.0,
        noisepriors=([0.0, 0.1, 1.0, 0.1], [0.0, 0.1, 1.0, 0.1]),
        probfn=(StochasticGene.prob_Gaussian, StochasticGene.prob_Gaussian),
        zeromedian=false,
    )
end

"""
    fit_fullstack_rna(; gene="GENE1", kwargs...)

Run a small full-stack fit against `data/rna/<gene>_COND.txt`.
"""
function fit_fullstack_rna(; gene::AbstractString=FULLSTACK_GENES[1], kwargs...)
    unit = findfirst(==(gene), FULLSTACK_GENES)
    unit === nothing && throw(ArgumentError("unknown full-stack gene $(repr(gene))"))
    return StochasticGene.fit(;
        _fullstack_common_kwargs()...,
        _fullstack_sampling_kwargs(; kwargs...)...,
        _rna_model_kwargs(unit)...,
        datatype="rna",
        datapath="rna",
        gene=gene,
        datacond=FULLSTACK_COND,
        label="fullstack-rna-$(gene)",
    )
end

"""
    fit_fullstack_rnacount(; gene="GENE1", kwargs...)

Run a small full-stack fit against `data/rnacount/<gene>_COND.txt`.
"""
function fit_fullstack_rnacount(; gene::AbstractString=FULLSTACK_GENES[1], kwargs...)
    unit = findfirst(==(gene), FULLSTACK_GENES)
    unit === nothing && throw(ArgumentError("unknown full-stack gene $(repr(gene))"))
    return StochasticGene.fit(;
        _fullstack_common_kwargs()...,
        _fullstack_sampling_kwargs(; kwargs...)...,
        _rna_model_kwargs(unit)...,
        datatype="rnacount",
        datapath="rnacount",
        gene=gene,
        datacond=FULLSTACK_COND,
        label="fullstack-rnacount-$(gene)",
    )
end

"""
    fit_fullstack_trace(; gene="GENE1", kwargs...)

Run a small full-stack fit against one gene from the shared `data/trace` folder.
"""
function fit_fullstack_trace(; gene::AbstractString=FULLSTACK_GENES[1], kwargs...)
    gene in FULLSTACK_GENES || throw(ArgumentError("unknown full-stack gene $(repr(gene))"))
    return StochasticGene.fit(;
        _fullstack_common_kwargs()...,
        _fullstack_sampling_kwargs(; kwargs...)...,
        _trace_model_kwargs()...,
        datatype="trace",
        datapath="trace",
        gene=gene,
        datacond="$(gene)_$(FULLSTACK_COND)",
        traceinfo=(1.0, 1, -1, 1.0, 0.0),
        datacol=3,
        label="fullstack-trace-$(gene)",
    )
end

"""
    fit_fullstack_tracejoint(; kwargs...)

Run a small coupled full-stack fit against paired traces from the shared `data/trace` folder.
"""
function fit_fullstack_tracejoint(; kwargs...)
    return StochasticGene.fit(;
        _fullstack_common_kwargs()...,
        _fullstack_sampling_kwargs(; kwargs...)...,
        _tracejoint_model_kwargs()...,
        datatype="tracejoint",
        datapath="trace",
        gene=FULLSTACK_GENES[1],
        datacond=FULLSTACK_TRACEJOINT_CONDS,
        traceinfo=(1.0, 1, -1, [1.0, 1.0], [0.0, 0.0]),
        datacol=3,
        label="fullstack-tracejoint",
    )
end

"""
    fit_fullstack_dwelltime(; gene="GENE1", kwargs...)

Run a small full-stack fit against one dwell-time histogram file.
"""
function fit_fullstack_dwelltime(; gene::AbstractString=FULLSTACK_GENES[1], kwargs...)
    unit = findfirst(==(gene), FULLSTACK_GENES)
    unit === nothing && throw(ArgumentError("unknown full-stack gene $(repr(gene))"))
    return StochasticGene.fit(;
        _fullstack_common_kwargs()...,
        _fullstack_sampling_kwargs(; kwargs...)...,
        _rna_model_kwargs(unit)...,
        datatype="dwelltime",
        datapath=["dwelltime/$(gene)_$(FULLSTACK_COND)_OFF.txt"],
        gene=gene,
        datacond=FULLSTACK_COND,
        dttype=["OFF"],
        onstates=[Int[]],
        label="fullstack-dwelltime-$(gene)",
    )
end

const FULLSTACK_FIT_CASES = (
    rna=fit_fullstack_rna,
    rnacount=fit_fullstack_rnacount,
    trace=fit_fullstack_trace,
    tracejoint=fit_fullstack_tracejoint,
    dwelltime=fit_fullstack_dwelltime,
)

function _selected_cases(selection)
    selection === nothing && return keys(FULLSTACK_FIT_CASES)
    names = Symbol.(split(String(selection), ","))
    unknown = [name for name in names if !haskey(FULLSTACK_FIT_CASES, name)]
    isempty(unknown) || throw(ArgumentError("unknown full-stack fit cases: $(join(unknown, ", "))"))
    return names
end

"""
    run_fullstack_fits!(; cases=nothing, regenerate=true, kwargs...)

Generate fixtures if requested and run selected developer full-stack fits. Use
`cases=:rna` or `cases="rna,trace"` to restrict execution.
"""
function run_fullstack_fits!(; cases=nothing, regenerate::Bool=true, kwargs...)
    regenerate && generate_fullstack_data!()
    mkpath(joinpath(DEFAULT_ROOT, FULLSTACK_RESULTFOLDER))
    outputs = Dict{Symbol,Any}()
    for case in _selected_cases(cases)
        println("Running full-stack fit case: ", case)
        outputs[case] = FULLSTACK_FIT_CASES[case](; kwargs...)
    end
    println("Full-stack results written to: ", joinpath(DEFAULT_ROOT, FULLSTACK_RESULTFOLDER))
    return outputs
end

if abspath(PROGRAM_FILE) == @__FILE__
    cases_env = get(ENV, "SG_FULLSTACK_CASES", "")
    cases = isempty(cases_env) ? nothing : cases_env
    run_fullstack_fits!(; cases=cases)
end
