name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.4'

      - name: Install dependencies
        run: |
          # First, install the main package dependencies
          julia --project=. -e 'import Pkg; Pkg.instantiate()'
          # Then install the docs dependencies
          cd docs
          julia --project=. -e 'import Pkg; Pkg.instantiate()'
          cd ..

      - name: Build and deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd docs
          julia --project=. -e 'include("make.jl")'
