name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.4'

      - name: Setup Julia environment
        run: |
          # Create a fresh environment for the package
          julia --project=. -e 'import Pkg; Pkg.activate("."); Pkg.instantiate(); Pkg.precompile()'
          # Create a fresh environment for docs
          julia --project=docs -e 'import Pkg; Pkg.activate("."); Pkg.instantiate(); Pkg.precompile()'

      - name: Build documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Build the package first to ensure it's precompiled
          julia --project=. -e 'import Pkg; Pkg.build("StochasticGene")'
          # Build documentation using Documenter's built-in functionality
          julia --project=docs -e 'import Pkg; Pkg.build("Documenter"); include("docs/make.jl")'
          
          # Configure git for deployment
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Add CNAME file for custom domain
          echo "stochasticgene.github.io" > docs/CNAME
          git add docs/CNAME
          git commit -m "Add CNAME file"
          
          # Push to gh-pages branch
          git push origin gh-pages --force
